{
 "title": "Application dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Release", "query": "label_values(release)" }
  ]
 },
 "panels": [
  {
   "title": "Crawler site connection time 95 procentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_site_connection_time_bucket{app=\"search-engine\",release=~\"^$Release$\"}[1m])) by (release,le))",
     "legendFormat": "{{ release }}"
    }
   ]
  },
  {
   "title": "Web page gen 95 procentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(web_page_gen_time_bucket{app=\"search-engine\",release=~\"^$Release$\"}[1m])) by (release,le))",
     "legendFormat": "{{ release }}"
    }
   ]
  },
  {
   "title": "Crawler page parse time 95 procentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_page_parse_time_bucket{app=\"search-engine\",release=~\"^$Release$\"}[1m])) by (release,le))",
     "legendFormat": "{{ release }}"
    }
   ]
  },
  {
   "title": "Web pages  served rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(web_pages_served{app=\"search-engine\",release=~\"^$Release$\"}[1m])",
     "legendFormat": "{{ release }}"
    }
   ]
  },
  {
   "title": "Crawler pages parsed rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_pages_parsed{app=\"search-engine\",release=~\"^$Release$\"}[1m])",
     "legendFormat": "{{ release }}"
    }
   ]
  }
 ]
}