{
 "title": "RabbitMQ Monitoring",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(rabbitmq_running, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rabbitmq_running{node=\"$node\",job=\"rabbitmq-endpoints\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rabbitmq_running{node=\"$node\",job=\"rabbitmq-endpoints\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rabbitmq_running{node=\"$node\",job=\"rabbitmq-endpoints\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Connections, channels and consumers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connectionsTotal{job=\"rabbitmq-endpoints\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "rabbitmq_channelsTotal{job=\"rabbitmq-endpoints\"}",
     "legendFormat": "channels"
    },
    {
     "expr": "rabbitmq_consumersTotal{job=\"rabbitmq-endpoints\"}",
     "legendFormat": "consumers"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_running{job=\"rabbitmq-endpoints\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{job=\"rabbitmq-endpoints\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_ready{job=\"rabbitmq-endpoints\"})",
     "legendFormat": "{{queue}}:ready"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_published_total{job=\"rabbitmq-endpoints\"})",
     "legendFormat": "{{queue}}:published"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_delivered_total{job=\"rabbitmq-endpoints\"})",
     "legendFormat": "{{queue}}:delivered"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_unacknowledged{job=\"rabbitmq-endpoints\"})",
     "legendFormat": "{{queue}}:unack"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_disk_free{job=\"rabbitmq-endpoints\"}",
     "legendFormat": "{{node}}:free"
    },
    {
     "expr": "rabbitmq_node_disk_free_limit{job=\"rabbitmq-endpoints\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{job=\"rabbitmq-endpoints\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{job=\"rabbitmq-endpoints\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  }
 ]
}