---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    app: efk
    component: fluent
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: efk
      component: fluent
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        kubernetes.io/cluster-service: "true"
        app: efk
        component: fluent
        release: {{ .Release.Name }}
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: {{ template "fluentd.fullname" . }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: {{ printf "%s-varlog" (include "fluentd.fullname" .) }}
          mountPath: /var/log
        - name: {{ printf "%s-varlibdockercontainers" (include "fluentd.fullname" .) }}
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: {{ printf "%s-libsystemddir" (include "fluentd.fullname" .) }}
          mountPath: /host/lib
          readOnly: true
        - name: {{ printf "%s-config-volume" (include "fluentd.fullname" .) }}
          mountPath: /etc/fluent/config.d
      nodeSelector:
        beta.kubernetes.io/fluentd-ds-ready: "true"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ printf "%s-varlog" (include "fluentd.fullname" .) }}
        hostPath:
          path: /var/log
      - name: {{ printf "%s-varlibdockercontainers" (include "fluentd.fullname" .) }}
        hostPath:
          path: /var/lib/docker/containers
      # It is needed to copy systemd library to decompress journals
      - name: {{ printf "%s-libsystemddir" (include "fluentd.fullname" .) }}
        hostPath:
          path: /usr/lib64
      - name: {{ printf "%s-config-volume" (include "fluentd.fullname" .) }}
        configMap:
          name: {{ printf "%s-config" (include "fluentd.fullname" .) }}
