version: '3.3'
services:
  mongodb:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      back_net:

  rabbitmq:
    image: bitnami/rabbitmq:3.7.11
    environment:
      - RABBITMQ_PASSWORD=rmq_pass
      - RABBITMQ_USERNAME=rmq_user
    networks:
      back_net:

  search_engine_crawler:
    image: ${USERNAME}/search_engine_crawler:${UI_V}
    depends_on:
      - rabbitmq
    networks:
      back_net:

  search_engine_ui:
    image: ${USERNAME}/search_engine_ui:${UI_V}
    networks:
      - back_net
      - front_net
    ports:
      - ${PORT}:8000/tcp

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
