---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: searchengine
    component: ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - name: ui
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: searchengine
    component: ui
    release: {{ .Release.Name }}
