---
- name: Install tiller
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    k8s_kubeconfig: ~/.kube/config
    k8s_manifests_base_dir: ../k8s-manifests/
    k8s_manage_namespace: false
    k8s_manifests:
      - tiller

  roles:
    - role: geerlingguy.k8s_manifests
