---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: searchengine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchengine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: searchengine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: crawler
        env:
          - name: MONGO
            value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
          - name: RMQ_HOST
            value: {{ .Values.rabbitMQHost | default (printf "%s-rabbitmq" .Release.Name) }}
          - name: RMQ_USERNAME
            value: user
          - name: RMQ_PASSWORD
            value: password
          - name: EXCLUDE_URLS
            value: {{ .Values.excluded_urls }}
