---
- name: Init helm
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Get tiller pod name
      k8s_facts:
        api_version: v1
        kind: Pod
        namespace: kube-system
        label_selectors:
          - app = helm
          - name = tiller
      register: tiller_pod

    - name: debug task
      debug:
        msg: "{{ tiller_pod.resources[0].metadata.name }}"

    # - name : Open tunnel connection to tiller pod
    #   shell: kubectl port-forward {{ tiller_pod.resources[0].metadata.name }} -n kube-system 44134:44134 >/dev/null &
    #   register: yum_sleeper

      # port-forward tiller-deploy-689d79895f-vs7rv 44134:44134 -n kube-system 

    - name: Install nginx-controller
      helm:
        host: localhost
        chart:
          name: nginx-ingress
          source:
            type: repo
            location: https://kubernetes-charts.storage.googleapis.com
        state: present
        name: nginx
        namespace: default
      ignore_errors: yes


    - name: Install prometheus
      helm:
        host: localhost
        chart:
          name: search-engine
          source:
            type: repo
            location: ./charts/search-engine
        state: present
        name: prometheus
        namespace: default

# prometheus charts/prometheus
