dependencies:
  - name: elasticsearch
    version: "1.0.0"
    repository: "file://../elasticsearch"
  - name: fluentd
    version: "1.5.1"
    repository: "file://../fluentd"
  - name: kibana
    version: "1.5.1"
    repository: "file://../kibana"
