elasticsearch:
  service:
    dbInternalPort: 9200
    transportInternalPort: 9300

  image:
    name: elasticsearch
    tag: 6.6.0

fluentd:
  service:
    dbInternalPort: 9200

  image:
    name: gcr.io/google-containers/fluentd-elasticsearch
    tag: v2.0.2

kibana:
  ingress:
    enabled: true
    hosts:
      - kibana.otus.garbar.pro
  # files:
  #   kibana.yml:
  #     elasticsearch.url: http://efk-elasticsearch:9200
  env:
    ELASTICSEARCH_URL: http://efk-elasticsearch:9200
